### PR TITLE
Update webclient management of cookies

### PR DESCRIPTION
**Pull request by Sanmoo**
Hi @jjohnson42 Jarrod,
Could you please review this PR? I think the caller should have the ability to add more cookies besides the ones already captured by the client. Please let me know if you have a different understanding.

Thanks =)

### CODE REVIEW

**Comment by openstack-gerrit** [comment]
Thank you for contributing to openstack/pyghmi!

openstack/pyghmi uses Gerrit for code review.

If you have never contributed to OpenStack before make sure you have read the
getting started documentation:
http://docs.openstack.org/infra/manual/developers.html#getting-started

Otherwise please visit
http://docs.openstack.org/infra/manual/developers.html#development-workflow
and follow the instructions there to upload your change to Gerrit.

**Comment by jjohnson42** [comment]
Sorry about the auto-close by openstack. 

Would you like me to make the change myself, or would you like to submit it to the openstack workflow (review.openstack.org) so credit is better preserved?

**Comment by Sanmoo** [comment]
That's ok. Feel free to change the code yourself.

**Comment by jjohnson42** [comment]
https://review.openstack.org/#/c/530800/

How's that look?  I pulled from this request so the author and everything should be intact, just committed by changing.

**Comment by Sanmoo** [comment]
Looks good to me.
Thanks =)

**Pull request closed without merging**
